---
output:
  md_document:
    variant: markdown_github
  github_document: default
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# The simexvsmecor Package
This package for R entails the code to execute a simulation study
and the code used to analyse the output of the simulation study, 
accompanying the manuscript "Random measurement error correction in an exposure 
by means of regression calibration and simulation-extrapolation". The aim of the
simulation study is the comparison between the simex and mecor package for 
measurement error correction. 

The first part of this package consist out of a 
simulation study comparing regression calibration and simulation-extrapolation
for a linear model with a continuous outcome. The second part of this simulation
study consist out of a simulation study comparing regression calibration and 
simulation-extrapolation for a logistic regression. The files for the second 
part are indicated with a suffix '_logreg'. In addition, a small replication of
the simulation study by Perrier et al. was done, which can be found in the files
indicated with the suffix '_perrier'. 

# Installation
The package can be installed via
```r
devtools::install_github("LindaNab/simexvsmecor", ref = "main")
```

# Quick demo
```r
library(simexvsmecor)
# view input data
data(input)
# run scenenario no. 1 of the simulation study with 100 replicates
run_sim(nrep = 100, scen_no = 1)
```
